sudo: false

rvm:
  - 2.3.1

before_install:
  - wget --no-check-certificate https://releases.hashicorp.com/packer/0.10.2/packer_0.10.2_linux_amd64.zip && unzip -d packer packer_0.10.2_linux_amd64.zip

before_script:
  - export PATH=$PATH:$PWD/packer
  - ~/bin/packer -v || true

script:
  - cd "${TRAVIS_BUILD_DIR}/" && find . -name '*.json' -exec packer validate {} \;

notification:
  email:
    on_success: never
